### ISSUE TITLE
How to create my own icons?

### ISSUE THREAD

**Issue by kun-zhou** [x11tete11x/dropbox-plasma-dark-icons#1]
Hello! Thank you for the nice icons set. I have always wanted to implement my own icons. I read your source code and it seems like you simply put the icons in `hicolor` directory. Reading the specification from for icon theme freedsktop.org, I understand that this directory will be looked up when icons are needed. However, I also noticed that you implemented the systray icons. My question is how did you know the systray icons should be named the way they are? Are there any websites I should read more about setting customized icons for systray? I think the .desktop file only specified the name of the main App icon, not the systray icons.

**Comment by x11tete11x** [comment]
Hi! sorry for late answer, i was on vacations :D, sure, i just see how some pkgbuilds of Archlinux does this, what routes they take, then, i just make the icons and put the same names, btw searching in hidden folders, BTW this is Dropbox specific "hack", perhaps you should see this (i dont tried it yet ): https://github.com/bil-elmoussaoui/Hardcode-Tray

thx for your interest!

EDIT: to be more "clear" what i wanna say with "hack" look this: http://www.alexl.netsons.org/blogposts/monochrome-systray-icon-for-telegram/ (this is how to put telegram tray icon in monochrome, again it's specific for telegram and he found it searching in hidden folders and so on, where telegram has his icons :D)

**Comment by kun-zhou** [comment]
Thank you for pointing me to so many resources! I'll definitely look into them. I have been working on understanding all the main icons in KDE, i.e., desktop entries, directories entries, etc, even when the specs from freedesktop.org are available, a good deal of experimentation is still needed.
